### ISSUE TITLE
Chronos timers overflow giving bad comparisons (TimerStore)

### ISSUE THREAD

**Issue by TygerBurning** [Metaswitch/chronos#156]
Running existing unit tests on Chronos fails on TestTimerStore tests

```
[  FAILED  ] 12 tests, listed below:
[  FAILED  ] TestTimer.FromJSONTests
[  FAILED  ] TestTimerStore.NearGetNextTimersTest
[  FAILED  ] TestTimerStore.NearGetNextTimersOffsetTest
[  FAILED  ] TestTimerStore.MidGetNextTimersTest
[  FAILED  ] TestTimerStore.LongGetNextTimersTest
[  FAILED  ] TestTimerStore.ClashingMultiMidGetNextTimersTest
[  FAILED  ] TestTimerStore.SeparateMultiMidGetNextTimersTest
[  FAILED  ] TestTimerStore.MultiLongGetTimersTest
[  FAILED  ] TestTimerStore.ReallyLongTimer
[  FAILED  ] TestTimerStore.Non10msShortTimerUpdate
[  FAILED  ] TestTimerStore.Non10msMediumTimerUpdate
[  FAILED  ] TestTimerStore.MixtureOfTimerLengths
```

Debugging reveals that when the TimerStore checks whether the timer should have already popped, the `next_pop_time` is considerably different to the `_tick_timestamp`

```
195       uint64_t next_pop_time = t->next_pop_time();
(gdb) next
198       if (next_pop_time < _tick_timestamp)
(gdb) next
207         TRC_WARNING("Modifying timer after pop time (current time is %lu). "
(gdb) next
210                     TIMER_LOG_PARAMS(t));
(gdb) print next_pop_time
$1 = 17800134
(gdb) print _tick_timestamp
$2 = 4312767330
```

It may be worth noting the Hex values for these times are:

```
(gdb) printf "%lx\n", _tick_timestamp
1010f9b62
(gdb) printf "%lx\n", next_pop_time
10f9bc6
```

It appears this may be an integer overflow error within the `next_pop_time` function. Looking into this further, the overflow appears to stem from `start_time_mono_ms`, see [here](https://github.com/Metaswitch/chronos/blob/dev/src/include/timer.h#L118). This could be resolved by making it a `uint64_t` rather than `uint32_t

On this topic, why is [this](https://github.com/Metaswitch/chronos/blob/dev/src/main/timer.cpp#L567) and [this](https://github.com/Metaswitch/chronos/blob/dev/src/main/timer.cpp#L556) a valid point, as why would we prefer it to wrap over if `next_pop_time` uses `start_time_mono_ms`

Do you agree with my logic, and do you know where the second comment stems from?

Thanks

**Comment by eleanor-merry** [comment]
@bossmc - passing to you as I think this relates to the change you made for #85

**Comment by bossmc** [comment]
Yep, like an accurate diagnosis, the `_tick_timestamp` is a `uint64_t` and we're comparing it to a `uint32_t` which might have wrapped (in this case because the host OS has been running for over 2^32 ms = ~50 days).

Since we work in wrapped 32-bit numbers everywhere else, the fix looks to be to do this comparison more carefully and treat a smaller number as bigger than a bigger number if the difference between them is > 2^31.  This restricts timer intervals to be no more than 25 days, but this doesn't seem too critical.

**Comment by bossmc** [comment]
@TygerBurning You're going to give this a bash as you're already elbows-deep in the chronos code.

**Comment by TygerBurning** [comment]
Fixed by https://github.com/Metaswitch/chronos/pull/159
