### ISSUE TITLE
Statistics aren't as accurate due to time taken to pop timers and repeat timers

### ISSUE THREAD

**Issue by TygerBurning** [Metaswitch/chronos#158]
As timers are removed and readded if they are repeated, current implementation may skew the statistics into thinking there is a higher flow of timers rather than just repeat timers being added again

In addition, the variance may be skewed due to the time taken to report the change in timer count, due to having to iterate through the `next_timers` set

**Comment by mirw** [comment]
@TygerBurning, are you OK to fix this as part of your work next sprint?

**Comment by mirw** [comment]
This was fixed a while ago.
