### ISSUE TITLE
Phantom chronos running after reboot

### ISSUE THREAD

**Issue by dtheobald** [Metaswitch/chronos#164]
After a reboot I noticed a phantom chronos running (i.e. /var/run/chronos.pid does not contain the process's pid). This causes monit to continually try to start another chronos, but (of course) it can't because one is already running and bound to its port. If I put the phantom chronos' pid in /var/run/chronos.pid, all is good and the system functions normally. I've only seen this sporadically in our lab, so its not easily reproduced.

Diags are available.

**Comment by rkd-msw** [comment]
https://github.com/Metaswitch/chronos/pull/191 should prevent this from happening. Can you watch out for this problem happening again, and close the issue if it doesn't happen again?
