### ISSUE TITLE
Chronos should have an internal community string

### ISSUE THREAD

**Issue by TygerBurning** [Metaswitch/chronos#167]
When Chronos performs a resync, [it uses stats] (https://github.com/Metaswitch/chronos/blob/dev/debian/chronos.init.d#L142) to determine when the resync is complete. If a user changes the community string, it will break this check, and so there should be an internal community string used for internal checks such as these

**Comment by mirw** [comment]
Since changing the community string is a legitimate (and sensible) user operation, and this breaks Chronos' resync behavior with no real workaround, marking this as high priority.

**Comment by mirw** [comment]
I'll fix this.
