### ISSUE TITLE
Walking the infinite timer table quickly gives corrupt data

### ISSUE THREAD

**Issue by rkd-msw** [Metaswitch/chronos#185]
Due to https://github.com/Metaswitch/clearwater-infrastructure/issues/259, my snmpwalk command attempted to walk the infinite timer table. It tried a GETNEXT request on iso.2.826.0.1.1578918.999, which returned iso.2.826.0.1.1578918.999.65.2 - this isn't a valid OID in that table. (It looks like it's trying to start with "A", which is 65 in ASCII, but it's missing the length OID and one of the column OIDs - I think the first entry should be iso.2.826.0.1.1578918.999.1.65.2.1.)

We then get further GETNEXTs based on what we've returned:
iso.2.826.0.1.1578918.999.65.2
iso.2.826.0.1.1578918.999.65.2.65.2
iso.2.826.0.1.1578918.999.65.2.65.2.1.2
iso.2.826.0.1.1578918.999.65.2.65.2.1.2.2415919136.2
iso.2.826.0.1.1578918.999.65.2.65.2.1.2.2415919136.2.2.1
iso.2.826.0.1.1578918.999.65.2.65.2.1.2.2415919136.2.2.1.0.0
iso.2.826.0.1.1578918.999.65.2.65.2.1.2.2415919136.2.2.1.0.0 (repeatedly)

Because the 65 is in the wrong place, it's treated as a length OID, and so we try and read 65 subsequent characters out of memory, and store them in our fixed-length OID buffer which can only store 64 OIDs. Often this hits a NULL byte somewhere and is cut short, but eventually it's long enough to overflow the OID buffer and the stack, so we crash with:

```
#9  0x00007f6af284dc9c in __GI___fortify_fail (msg=<optimized out>, msg@entry=0x7f6af28c2513 "stack smashing detected") at fortify_fail.c:37
#10 0x00007f6af284dc40 in __stack_chk_fail () at stack_chk_fail.c:28
```

**Comment by rkd-msw** [comment]
This is the root cause of https://github.com/Metaswitch/cpp-common/issues/393. Note that I think this is lower priority than https://github.com/Metaswitch/clearwater-infrastructure/issues/259 - even if we fix this, we'll just spin forever trying to read an infinite table.

**Comment by rkd-msw** [comment]
@bossmc - you fixed this, right?

**Comment by bossmc** [comment]
Yep!
