### ISSUE TITLE
CHRONOS_TIMER_POP_ERROR alarm is never cleared, and also possibly shouldn't be an alarm

### ISSUE THREAD

**Issue by graemerobertson** [Metaswitch/chronos#219]
From reading the code, it looks as though the CHRONOS_TIMER_POP_ERROR alarm is set in the [timer_handler](https://github.com/Metaswitch/chronos/blob/8c632fe74a24791fcf8b1026913b399c18a1e39a/src/main/timer_handler.cpp#L307) but never cleared. It feels like a) we should definitely clear this alarm at some point and b) it doesn't make much sense as an alarm anyway. Currently we could have tried to pop a solitary timer for a solitary rogue service and that sets the alarm forever.

**Comment by bossmc** [comment]
My gut feeling is that this isn't an alarm-able condition on it's own.  The client chooses the callback URL on a per-timer basis, so there's no correlation between one timer succeeding and another failing.

If we really want a (nearly) equivalent alarm, we could raise one if all timer pops fail for a window of time (like the `CommunicationMonitor` does, but across all callback URLs).  I'm not sure what we could do instead, certainly if we had SAS, this would be a good candidate for a SAS event...
