### ISSUE TITLE
Chronos cluster high availability

### ISSUE THREAD

**Issue by chandu-atina** [Metaswitch/chronos#225]
I have three server A,B,C on each machine I'm running chronos, zookeeper, mesos-master, mesos-slave.

Chronos cantact mesos-master using zookeeper url hence it automatically picks leading master even if some node is down. I'm having high availability here.

Even Chronos run in cluster mode so accessing any of the Chronos I see same list of jobs and everything works fine.

Problem I have here is, Chronos is accessible with any of the three URLs

http://server_node_1:4400
http://server_node_2:4400
http://server_node_3:4400

I have another application which schedules jobs in Chronos using Rest API. Which URL my application has to talk to in order in run in high availabiity mode?

Let's say my application talks to http://server_node_1:4400 for scheduling the job, if chronos on node server_node_1 is down I'm not able to schedule the Job.

My application needs to talk to single URL in order to schedule job in Chronos. Even if some Chronos node is down, I should be able to schedule the job. Do I need to have some kind of load balancer between my application and Chronos cluster to pick running chronos node for job scheduling? How can I achieve high availability in my scenario?

**Comment by chris-elford-metaswitch** [comment]
It is great to hear that you are using Chronos.

Have you read our technical introduction (here)[https://github.com/Metaswitch/chronos/blob/dev/doc/technical.md]?

Chronos automatically replicates each timer to another node in the cluster, which will pop the timer if the first node fails. This gives high-availability. You can take advantage of this by sending timers to the instance of Chronos on the same machine as the process using the timer without needing to set up any load balancing.

**Comment by rkd-msw** [comment]
Hi @chandu-atina - it looks like you're asking about the Chronos component of Mesos (https://mesos.github.io/chronos/) which is a job scheduler, whereas this is about the Chronos component of Project Clearwater (http://www.projectclearwater.org/technical/clearwater-architecture/), which is a distributed timer store.

As such, I'm going to close this issue - please let me know if I've misunderstood and you're tot talking about the Mesos component.
