### ISSUE TITLE
Chronos should work out when it needs to build dependencies

### ISSUE THREAD

**Issue by chris-elford-metaswitch** [Metaswitch/chronos#227]
Currently, building Chronos requires that the user run `make submodules` each time any submodule is modified. Our makefile should detect this and run the command when it needs to be run.

This would remove one of the differences between the build infrastructure in our different projects.

**Comment by graemerobertson** [comment]
This is the same as https://github.com/Metaswitch/chronos/issues/215 I think

**Comment by chris-elford-metaswitch** [comment]
You're right, I'll close this as a duplicate.
