### ISSUE TITLE
Updating timers for >1 hour into the future is inefficient

### ISSUE THREAD

**Issue by rkd-msw** [Metaswitch/chronos#258]
#### Symptoms

When we remove a timer in the timer heap (which we do as part of updating a timer), [we iterate through the whole heap to find that timer](https://github.com/Metaswitch/chronos/blob/543b60abc1a4e0f060cf3d8b8accf2d6647a721c/src/timer_store.cpp#L386). This is O(n) efficiency - whereas we want to aim for O(log n) or O(1) efficiency with timer operations.

#### Impact

High CPU usage (e.g. Chronos can use as much CPU as Sprout when this is happening).

#### Release and environment 

All Chronos releases.

#### Steps to reproduce

Run REGISTER load with an expiry time greater than one hour.

**Comment by graemerobertson** [comment]
I've seen Chronos using as much CPU as Sprout with REGISTER load with an expiry time of a week.

Under REGISTER load with an expiry of a day, Chronos seems to run at a sensible CPU level.

**Comment by rkd-msw** [comment]
Fixed by #267.
