### ISSUE TITLE
Running 'service chronos wait-sync' waits forever

### ISSUE THREAD

**Issue by dtheobald** [Metaswitch/chronos#274]
#### Symptoms

Chronos won't cluster.

Upon closer inspection I discovered that 'service chronos wait-sync' is never completing because ```snmpget -Oqv -v2c -c clearwater localhost .1.2.826.0.1.1578918.9.10.1``` returns ```No Such Object available on this agent at this OID``` which the script is not expecting, so it waits forever.

That ```snmpget``` worked prior to release-101. Other SNMP features work as expected (i.e., alarms and statistics).

#### Impact

This is service affecting.

#### Release and environment 

release-101

#### Steps to reproduce
Bringing up a sprout or ralf node fails to cluster every time.

**Comment by eleanor-merry** [comment]
This is because of https://github.com/Metaswitch/cpp-common/pull/527, and it's been fixed by https://github.com/Metaswitch/chronos/pull/273. To work around the issue, kill the wait-sync process on the Sprout/Ralf node
