### ISSUE TITLE
Timers with interval 0 never get tombstoned

### ISSUE THREAD

**Issue by eleanor-merry** [Metaswitch/chronos#276]
#### Symptoms
If I add a timer with interval/repeat-for 0 to Chronos then I can end up in the situation where Chronos never deletes the timer.

When Chronos receives this timer it immediately puts it into the overdue timers bucket. The timer store always processes any timers in the overdue timers bucket each tick (https://github.com/Metaswitch/chronos/blob/dev/src/timer_store.cpp#L199). The timer handler then passes the timer to the callback, which tries to perform the callback and then passes the timer back to the timer handler (https://github.com/Metaswitch/chronos/blob/dev/src/timer_handler.cpp#L294).

The timer handler then decides whether to tombstone the timer. It does so if the timer's sequence_number + 1 * interval > repeat-for (https://github.com/Metaswitch/chronos/blob/dev/src/timer_handler.cpp#L297). This is never true in the case where interval/repeat-for is 0, so the timer handler adds it straight back into the overdue timers bucket. 

Fix is to check whether interval/repeat-for = 0 at https://github.com/Metaswitch/chronos/blob/dev/src/timer_handler.cpp#L297 and tombstone the timer if so.

**Comment by steelyvoid** [comment]
Adding myself as interested party

**Comment by AME2** [comment]
Fixed by https://github.com/Metaswitch/chronos/pull/279
