### ISSUE TITLE
Chronos GR: Error logs seen when restarting chronos

### ISSUE THREAD

**Issue by sathiyan-sivathas** [Metaswitch/chronos#296]
When testing 2-site GR with two Chronos nodes in each site, I see error logs when I restart Chronos.  I don't see these logs in a non-GR deployment.  The logs below are from sprout-1 and the address in the logs below `10.0.32.77` is from sprout-3, the other sprout node in site 1.

To reproduce:
- Spin up a Chronos GR deployment.
- Run `sudo service chronos restart`

Logs:
`23-09-2016 16:11:29.483 UTC Debug http_connection_pool.cpp:56: Allocated CURL handle 0x15d0e00`
`23-09-2016 16:11:29.483 UTC Debug connection_pool.h:246: Created new connection 0x1715690`
`23-09-2016 16:11:29.483 UTC Debug httpclient.cpp:464: Sending HTTP request : http://10.0.32.77:7253/timers?node-for-replicas=10.0.112.132;cluster-view-id=9224524329337110529;time-from=0 (trying 10.0.32.77)`
`23-09-2016 16:11:29.485 UTC Error httpclient.cpp:485: http://10.0.32.77:7253/timers?node-for-replicas=10.0.112.132;cluster-view-id=9224524329337110529;time-from=0 failed at server 10.0.32.77 : Couldn't connect to server (7) : fatal`
`23-09-2016 16:11:29.485 UTC Debug baseresolver.cpp:400: Add 10.0.32.77:7253 transport 6 to blacklist for 30 seconds, graylist for 30 seconds`
`23-09-2016 16:11:29.485 UTC Debug connection_pool.h:261: Release connection to IP: 10.0.32.77, port: 7253 and destroy`
`23-09-2016 16:11:29.485 UTC Debug connection_pool.h:225: Request for connection to IP: 10.0.32.77, port: 7253`
`23-09-2016 16:11:29.485 UTC Debug connection_pool.h:244: No existing connection in pool, create one`
`23-09-2016 16:11:29.485 UTC Debug http_connection_pool.cpp:56: Allocated CURL handle 0x15d0e00`
`23-09-2016 16:11:29.485 UTC Debug connection_pool.h:246: Created new connection 0x15ebd70
23-09-2016 16:11:29.485 UTC Debug httpclient.cpp:464: Sending HTTP request : http://10.0.32.77:7253/timers?node-for-replicas=10.0.112.132;cluster-view-id=9224524329337110529;time-from=0 (trying 10.0.32.77)`
`23-09-2016 16:11:29.486 UTC Error httpclient.cpp:485: http://10.0.32.77:7253/timers?node-for-replicas=10.0.112.132;cluster-view-id=9224524329337110529;time-from=0 failed at server 10.0.32.77 : Couldn't connect to server (7) : fatal`
`23-09-2016 16:11:29.486 UTC Debug baseresolver.cpp:400: Add 10.0.32.77:7253 transport 6 to blacklist for 30 seconds, graylist for 30 seconds`
`23-09-2016 16:11:29.486 UTC Debug connection_pool.h:261: Release connection to IP: 10.0.32.77, port: 7253 and destroy`
`23-09-2016 16:11:29.486 UTC Error httpclient.cpp:615: cURL failure with cURL error code 7 (see man 3 libcurl-errors) and HTTP error code 404`

**Comment by eleanor-merry** [comment]
I can't reproduce this with the current code - there's been a fair number of changes since this issue was raised so it's eminently plausible that this has been fixed
