### ISSUE TITLE
Chronos callback treats HTTP failure responses as OK

### ISSUE THREAD

**Issue by johadalin** [Metaswitch/chronos#312]
In testing https://github.com/Metaswitch/sprout/pull/1587, where sprout was made to respond 503 to all http requests, it was noticed that the subscription and registration timeout live-tests were failing.

This was due to the chronos timer pop receiving a 503 response, where sprout rejects the timer, but chronos notes that the callback was successful.
The check responsible for this is at  https://github.com/Metaswitch/chronos/blob/dev/src/http_callback.cpp#L139 
More properly, we should not treat _any_ http response as a success, but should be aware of the different http errors, and handle them reasonably; the sprout handlers appear to assume that chronos is already able to do this, in that it sends different responses for different types of request failure, at https://github.com/Metaswitch/sprout/blob/dev/src/handlers.cpp#L199

One reasonable way to go about reseolving this is to simply implement awareness of these errors in the http_callback methods, setting the curl option [CURLOPT_FAILONERROR](https://curl.haxx.se/libcurl/c/CURLOPT_FAILONERROR.html), which would lead to failures being raised, and then handled in https://github.com/Metaswitch/chronos/blob/dev/src/http_callback.cpp#L147

**Comment by sebrexmetaswitch** [comment]
Fixed in the above pull request
