### ISSUE TITLE
Chronos does not do any SAS logging indicating when it has failed to store a duplicate timer

### ISSUE THREAD

**Issue by AME2** [Metaswitch/chronos#327]
I was doing some resiliency testing using a deployment with two Sprouts, two Homesteads, a Ralf and an external HSS.
I had turned off the Chronos process on Sprout-2 and attempted to register a subscriber (which did register successfully).
During those registrations flows in which Sprout-1 asks Homestead for an authentication vector I was expecting to see Sprout logs along the following lines:

- Sprout-1 receives the authentication vector
- Sprout-1 successfully stores a (challenge timeout) timer using its local Chronos process
- The Chronos process on Sprout-1 fails to store a duplicate timer

#### Symptoms
In fact what I saw in SAS were the following logs:
- 14:22:32.966 Sprout-1 receives the authentication vector
- 14:22:32:969 Sprout-1 successfully stores a (challenge timeout) timer using its local Chronos process
- Nothing from Chronos indicating the health of the other Chronos process

Attached are a SAS log, wireshark trace, Sprout log and diags package.
[SAS incomplete when one Chronos down.zip](https://github.com/Metaswitch/chronos/files/682607/SAS.incomplete.when.one.Chronos.down.zip)

#### Impact
If something has genuinely gone wrong with a Chronos process then you wouldn't be alerted to it by reading these logs which could cause timers to be lost (for example after reading these logs you may feel everything is fine with Sprout-2 and take Sprout-1 offline temporarily). 

#### Release and environment 
2 Sprouts: 10.0.0-161216-~255.00.0
2 Homesteads: 10.0.0-161216-~255.00.0
1 Ralf: 10.0.0-161216-~255.00.0
1 real external HSS

#### Steps to reproduce
Create a deployment as above. On Sprout-2 run the following commands to stop the Chronos process:

```
sudo monit unmonitor chronos_process
sudo service chronos stop
```

Attempt to register subscribers until you get a registration where Sprout-1 is requesting the authentication vector.

**Comment by rkd-msw** [comment]
Isn't this expected behaviour? Chronos doesn't do any SAS logging by design, partly in order to keep SAS traffic down, partly because it's designed as a datastore rather than a service processing node (so is analogous to Memcached and Cassandra, neither of which log to SAS).

That said, if it's not possible to tell that something is wrong with a Chronos process (leading the operator to mistakenly shut off their only functioning node) that's bad. But I'd expect there to be an alarm in this case, and for that to be what alerted the operator - was there?

**Comment by AME2** [comment]
I'm closing this issue.

An alarm is raised when the Chronos process goes down, this is resent every 30 seconds so there's no risk of a user missing the problem.

My other concern was that SAS looks weird- we get a log for Sprout posting a timer to a Chronos but we don't get a log for Chronos replicating the timer to another Chronos. After our conversation I'm happy that because the latter of these is an internal process which a user doesn't need to know about, we don't make any logs.
