### ISSUE TITLE
Chronos is not robust to NTP time changes

### ISSUE THREAD

**Issue by rkd-msw** [Metaswitch/chronos#85]
At https://github.com/Metaswitch/chronos/blob/4c18b9d8c6e8826bdfdb7c0a022b38904821ec6b/src/main/timer_store.cpp#L94 we compare `timer->last_pop_time()` to `_tick_timestamp` to see if a timer is overdue. But `last_pop_time()` is CLOCK_REALTIME (it has to be, because it's shared across multiple Chronos nodes kept in sync by NTP) whereas `_tick_timestamp` is CLOCK_MONOTONIC (and again, it has to be - otherwise an NTP step change could cause long pauses at https://github.com/Metaswitch/chronos/blob/4c18b9d8c6e8826bdfdb7c0a022b38904821ec6b/src/main/timer_handler.cpp#L105).

This means that if NTP gets moved backwards during a Chronos run, all your timers get popped immediately until Chronos restarts.

Maybe there's some clever solution involving switching the timestamp to CLOCK_REALTIME only when we replicate timers, and never otherwise? But we'd have to avoid a repeat of https://github.com/Metaswitch/cpp-common/issues/160.

**Comment by bossmc** [comment]
Raising priority since NTP time shifts are common in virtualized environments.

**Comment by bossmc** [comment]
Alternatively Chronos could always work (internally) in "delta time", where the first Chronos to receive a client request works out how many seconds into the future it should pop and sends that to the other Chronos's in the cluster.  They all add the timer that far ahead of their monotonic time into their timer wheel (plus replication drift).  This means that any clock time discrepancy is coded into the original translation to delta time and every other Chronos will agree exactly (up to network latency).
