### ISSUE TITLE
Chronos may not support UTF-8 - need to investigate if this is true, and if it is a problem

### ISSUE THREAD

**Issue by AlexHockey** [Metaswitch/chronos#91]
On the response to a timer POST, Chronos returns the following content type header:

`Content-Type: text/html; charset=ISO-8859-1`

The speculation is that Chronos may not support UTF-8. If this is true, and if Clearwater can ever send it UTF-8 strings, we need to fix Chronos so it can support them.

**Comment by rkd-msw** [comment]
I tested this by feeding some Greek into Chronos, and it came out fine (with a Content-Type of 'application/octet-stream', which makes sense for opaque data):

```
POST / HTTP/1.1
Host: 127.0.0.1:5000
Accept: */*
X-Sequence-Number: 1
Content-Type: application/octet-stream
Content-Length: 83

ὕαλον ϕαγεῖν δύναμαι· τοῦτο οὔ με βλάπτει.
```

So I think this is OK to close - @AlexHockey, agree?

**Comment by AlexHockey** [comment]
Fine with me
